#!/bin/sh
    
commit_msg_file=$1
commit_msg=$(cat $commit_msg_file)

if ! echo "$commit_msg" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert): .+"; then
    echo "A mensagem de commit não segue o formato <tipo>: <breve descrição>"
    exit 1
fi