#!/bin/sh
# #!/usr/bin/env bash
 
# if ! echo "$commit_msg" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert): .{1,50}$"; then
if ! grep -iqE "^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert): .{1,50}$" "$1"; then
    echo "Mensagem de commit inválida. Por favor, siga o formato: <tipo>: <breve descrição>"
    exit 1
fi
