#!/bin/sh

branch_name=$(git branch --show-current)

case $branch_name in
    "feature/"*)
        prefix="feat"
        ;;
    "fix/"*)
        prefix="fix"
        ;;
    *)
        prefix="chore"
        ;;
esac

sed -i.bak -e "1s/^/$prefix: /" $1