name: Build and deploy Angular app to an Azure Web App

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  AZURE_WEBAPP_NAME: my-app-name  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'           # set this to the node version to use

jobs:
  build:
    name: Artefato - Código referente a tag
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        echo running build

  PlanAndTestDev:
    name: Planning and testing to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Planning DEV
        run: |
          echo "Planning & testing to dev result" >> $GITHUB_STEP_SUMMARY  
          
  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: PlanAndTestDev
    environment:
      name: "dev"

    steps:
      - name: "Deploy to Azure WebApp"
        run: |
          echo Running development
          
  PlanAndTestHom:
    name: Planning and testing to Hom
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deployDev
    steps:
      - name: Planning Hom
        run: |
          echo "Planning & tests to hom result" >> $GITHUB_STEP_SUMMARY  
  
  deployHom:
    name: Deploy to Homologation
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: PlanAndTestHom
    environment:
      name: "hom"
      
    steps:
      - name: "Deploy to Azure WebApp"
        run: |
          echo Running Homologation
          
  PlanAndTestProd:
    name: Planning and testing to Prod
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deployDev
    steps:
      - name: Planning PROD
        run: |
          echo "Planning & tests to prod result" >> $GITHUB_STEP_SUMMARY  
  
  deployProd:
    name: Deploy to Production
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: PlanAndTestProd
    environment:
      name: "prod"
      
    steps:
      - name: "Deploy to Azure WebApp"
        run: |
          echo Running Production
