name: Build and deploy Angular app to an Azure Web App

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  AZURE_WEBAPP_NAME: my-app-name  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'           # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build, and test
      run: |
        echo running build

    - name: Plan DEV
      run: |
        echo "Running dev environment" >> $GITHUB_STEP_SUMMARY  

    # - name: Zip artifact for deployment
    #   run: |
    #     zip release.zip ./* -r

    # - name: Upload artifact for deployment job
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: node-app
    #     path: ./release.zip

  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "dev"

    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: node-app

      # - name: unzip artifact for deployment
      #   run: unzip release.zip

      - name: "Deploy to Azure WebApp"
        run: |
          echo Running development
          
  PlanProd:
    name: Planning to Prod
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Planning PROD
        run: |
          echo "Running prod environment" >> $GITHUB_STEP_SUMMARY  
  
  deployProd:
    name: Deploy to Production
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deployDev
    environment:
      name: "prod"
      
    steps:
      # - name: Download artifact from build job
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: node-app

      # - name: unzip artifact for deployment
      #   run: unzip release.zip

      - name: "Deploy to Azure WebApp"
        run: |
          echo Running Production
