# This is a basic workflow to help you get started with Actions

name: Release Please

permissions:
  contents: write
  pull-requests: write
  packages: write

# Controls when the workflow will run
on:
  # push:
  #   branches:
  #     - 'main'
  pull_request:
    paths:
      - 'module/**'
    types:
      - closed
    branches:
      - 'main'  

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  release-please:
    runs-on: ubuntu-latest
    # needs: update-terraform-docs
    steps:  
      - name: Checkout
        uses: actions/checkout@v4
        
      - uses: google-github-actions/release-please-action@v3
        id: tag-release
        with:
          path: './module'
          changlog-path: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: terraform-module
          nonrepo-tags: true
          package-name: 'sbx-terraform-module'
          command: github-release
      
      - run: echo "Release created ${{ steps.tag-release.outputs.release_created }}"
